name: .NET Core

on:
  # Trigger the workflow on push or pull request,
  # but only on master branch
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://api.nuget.org/v3/index.json
      env: 
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_DEPLOY_KEY}}
        PACKAGE_VERSION: 1.2.1
        
    - name: create DialogStatus nuget package
      run: | 
        dotnet build "ProgressDialog/ProgressDialogStatus/ProgressDialogStatus.csproj" --configuration Release
        dotnet pack "ProgressDialog/ProgressDialogStatus/ProgressDialogStatus.csproj" --configuration Release

    - name: create nuget package
      run: |
        dotnet build "ProgressDialog/ProgressDialog/ProgressDialog.csproj" --source "../ProgressDialogStatus/bin/Release/" --configuration Release
        dotnet pack "ProgressDialog/ProgressDialog/ProgressDialog.csproj" --configuration Release
    
    - name: Publish to nuget
      run: | 
        dotnet nuget push "ProgressDialog/ProgressDialogStatus/bin/Release/ProgressDialogStatus.$PACKAGE_VERSION.nupkg" --api-key ${{secrets.NUGET_DEPLOY_KEY}} --skip-duplicate --no-symbols true
        dotnet nuget push "ProgressDialog/ProgressDialog/bin/Release/ProgressDialog.$PACKAGE_VERSION.nupkg" --api-key ${{secrets.NUGET_DEPLOY_KEY}} --skip-duplicate --no-symbols true
